Use urlib3 with certifi for downloading files over http and https
Because urlib3 doesn't support FTP, we use urlretrieve for non-http
downloads.

This fixes cert errors like the following:
  OSError: [Errno socket error] [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

The above error appears to be caused by the certs not being found,
whether in a venv or not. Using ceritfi explicitly seems to fix that.

Tested with:
  #!/bin/bash
  # exit when any command fails
  set -e
  set -o pipefail

  if [ ! -d py3env/bin/ ]; then
    python3 -m virtualenv -p python3 py3env
  fi

  source py3env/bin/activate

  brew install autoconf automake libtool libffi pkg-config 2>&1 | sed -e 's/^/BREW: /g'
  brew link libtool 2>&1 | sed -e 's/^/BREW LINK: /g'
  pip install -e ../ 2>&1 | sed -e 's/^/PIP INSTALL kivy: /g'
  python3 -m pip install --upgrade certifi 2>&1 | sed -e 's/^/PIP CERTIFY: /g'

  # fails at this stage with the above OSError without the patch
  toolchain build kivy 2>&1 | sed -e 's/^/build kivy: /g'