missing import
```
$ python3 toolchain.py build zbarlight
...
Traceback (most recent call last):
  File "toolchain.py", line 3, in <module>
    main()
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 1519, in main
    ToolchainCL()
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 1276, in __init__
    getattr(self, args.command)()
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 1337, in build
    build_recipes(args.recipe, ctx)
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 1127, in build_recipes
    recipe.execute()
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 699, in execute
    self.build_all()
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 793, in build_all
    self.build(arch)
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/toolchain.py", line 780, in build
    self.build_arch(arch)
  File "/Users/mflaxman/workspace/kivy-ios/kivy_ios/recipes/zbarlight/__init__.py", line 38, in build_arch
    shprint(hostpython, "setup.py", "build",   # noqa: F821
NameError: name 'shprint' is not defined
```

Even with this bugfix I'm still getting an error, but it could be specific to my environment.